### PR TITLE
Added fixity declaration for ./ operator and relaxed upper bound for len...

### LINKED ISSUE #4: Upper bounds for lens dependency
hexpat-lens is a super helpful package for me. Can you bump the lens dependency upper bound to `lens < 5.0` so that this can build with the `lens` on the latest stackage LTS snapshot? (I'm running it with lens 4.6.0.1 right now, so I know that works, but I'm pretty sure that lens hasn't made any breaking changes since then).

### PR DESCRIPTION
**Pull request by andrewthad**
...s dependency

Resolves #4 and #5.

### CODE REVIEW

**Comment by tel** [comment]
This looks very good. I'll merge it in.

**Comment by tel** [comment]
I'll also bake a new Cabal release shortly

**Comment by tel** [comment]
Here we are! http://hackage.haskell.org/package/hexpat-lens-0.1.3

**Comment by tel** [comment]
Finally, if you're using hexpat-lens currently and are interested in getting a commit bit on this repo then I'd be more than happy to provide one.

**Comment by andrewthad** [comment]
I would greatly appreciate that. Thanks!

**Comment by tel** [comment]
There you go!

**Pull request merged**
